CL\Slack\Payload\ChatUpdatePayload:
    properties:
        ts:
            type: string
        channel:
            type: string
        text:
            type: string
        attachments:
            type: string
            accessor:
                getter: getAttachmentsJson
        parse:
            type: string
        linkNames:
            type: string
        asUser:
            type: boolean
