CL\Slack\Payload\ChatPostMessagePayload:
    exclusion_policy: ALL
    properties:
        channel:
            type: string
        text:
            type: string
        parse:
            type: string
        linkNames:
            type: string
        attachments:
            type: string
            accessor:
                getter: getAttachmentsJson
        unfurlLinks:
            type: string
        unfurlMedia:
            type: string
        username:
            type: string
        asUser:
            type: boolean
        iconUrl:
            type: string
        iconEmoji:
            type: string
        threadTs:
            type: string
        replyBroadcast:
            type: string